from openai import OpenAI
import os

client = OpenAI(api_key=os.environ['open_ai_key'])

# Function to interact with the OpenAI API
def ask_llm(prompt):
    """
    Sends a user prompt to an LLM (Language Model) and returns the model's response.

    This function interacts with an AI language model (in this case, `gpt-4o`) using 
    a predefined system message and the user-provided prompt. The model generates 
    a response with a maximum of 1000 tokens, and the temperature is set to 0 
    for deterministic outputs.

    Parameters:
    ----------
    prompt : str
        The prompt or question to be sent to the language model.

    Returns:
    -------
    str
        The response generated by the language model based on the given prompt.
    """
      
    response = client.chat.completions.create(
        model='gpt-4o',
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        temperature=0
    )
    return response.choices[0].message.content

def main(prompt: str):
    """
    This is the main entry point for the AI assistant.

    Args:
        prompt (str): The prompt to deliver to the LLM.
    """

    # Call the function and print the result
    return ask_llm(prompt)

if __name__ == '__main__':
    prompt = input('Please input your prompt...')

    message = main(prompt=prompt)
    print(message)